server:
  port: 80
spring:
  redis:
    database: 3
    host: 127.0.0.1
    #password: root
    port: 6379
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接