server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2-export
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5





